# Generated by Django 2.2.17 on 2021-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_auto_20210207_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(max_length=200, verbose_name='الاشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ الارسال'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الخدمه'),
        ),
    ]
