# Generated by Django 2.2.17 on 2021-02-06 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('title', models.CharField(max_length=10000, verbose_name='اسم الاذن')),
                ('price', models.FloatField(verbose_name='تكلفة الاذن')),
                ('content', models.TextField(blank=True, null=True, verbose_name=' المنصرف اليه')),
                ('id', models.CharField(default='21020649845', max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'اذن',
                'verbose_name_plural': 'الاذونات',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='نوع الخدمه')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, unique=True, verbose_name='اسم العميل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name=' ملاحظات')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='ملفات ميديا')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='الاسم  ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('content', models.TextField(verbose_name=' الرساله')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'طلب مساعده',
                'verbose_name_plural': 'طلبات المساعده',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, unique=True, verbose_name='اسم العامل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='رقم الهاتف')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='رقم هاتف ولي الأمر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name=' ملاحظات')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='ملفات ميديا')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='عنوان الخدمه')),
                ('time', models.CharField(max_length=10000, verbose_name='مدة عمل الخدمة')),
                ('price', models.FloatField(verbose_name='تكلفة الخدمه')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='نوع الخدمه')),
            ],
            options={
                'verbose_name': 'خدمه',
                'verbose_name_plural': 'الخدمات',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ بداية الخدمه')),
                ('date2', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ نهاية الخدمه')),
                ('price', models.FloatField(verbose_name='المبلغ المستحق')),
                ('discount', models.FloatField(verbose_name='الخصم')),
                ('paid', models.FloatField(verbose_name='المبلغ المدفوع')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client', verbose_name='العميل')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service', verbose_name='الخدمه')),
            ],
            options={
                'verbose_name': 'خدمة عمل',
                'verbose_name_plural': 'خدمات العملاء',
                'ordering': ('-date',),
            },
        ),
    ]
