# Generated by Django 2.2.17 on 2021-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210206_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='label',
            field=models.CharField(choices=[('A', 'قيد الانتظار'), ('B', 'تم التواصل'), ('C', 'مغلق')], default='A', max_length=1, verbose_name='الحاله'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='discount',
            field=models.FloatField(default=0, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='paid',
            field=models.FloatField(default=0, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='price',
            field=models.FloatField(default=0, verbose_name='المبلغ المستحق'),
        ),
    ]
