# Generated by Django 2.2.17 on 2021-02-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210206_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.Worker', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.Client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.Service', verbose_name='الخدمه'),
        ),
    ]
