# Generated by Django 2.2.17 on 2021-02-06 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210206_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='عنوان المقال')),
                ('المقال', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
