# Generated by Django 2.2.17 on 2021-02-06 10:00

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-date',), 'verbose_name': 'مقال', 'verbose_name_plural': 'المقالات'},
        ),
        migrations.AddField(
            model_name='posts',
            name='active',
            field=models.BooleanField(default=True, help_text='قم بالغاء التفعيل بدلا من الحذف ولن يظهر في الموقع', verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المقال'),
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default='notfound.png', upload_to='', verbose_name='صورة المقال'),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='المقال',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
