# Generated by Django 2.2.17 on 2021-02-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210206_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='clientservice',
            name='paid',
        ),
    ]
