# Generated by Django 2.2.17 on 2021-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210206_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientservice',
            options={'ordering': ('-date',), 'verbose_name': ' اشتراك خدمه', 'verbose_name_plural': 'اشتراكات الخدمات'},
        ),
        migrations.AddField(
            model_name='clientservice',
            name='active',
            field=models.BooleanField(default=True, verbose_name='خدمه جاريه'),
        ),
    ]
