# Generated by Django 2.2.17 on 2021-02-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210206_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='label',
            field=models.CharField(choices=[('A', 'خدمه جاريه'), ('B', 'ستنتهي قريبا'), ('C', 'منتهيه')], default='A', editable=False, max_length=1, verbose_name='الحاله'),
        ),
    ]
