# Generated by Django 2.2.17 on 2021-02-08 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='اسم الموقع')),
                ('content', models.TextField(verbose_name='وصف الموقع')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='من نحن')),
                ('email', models.EmailField(max_length=254, verbose_name='ايميل الموقع')),
                ('phone', models.CharField(max_length=1000, verbose_name='رقم الهاتف للموقع')),
                ('adrress', models.TextField(verbose_name='عنوان المكتب ')),
                ('active', models.BooleanField(default=True, verbose_name='تفعيل الموقع')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
            },
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(verbose_name='وصف المقال'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=10000, unique=True, verbose_name='عنوان المقال'),
        ),
    ]
