# Generated by Django 2.2.17 on 2021-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210208_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteedit',
            options={'verbose_name': 'اعدادات', 'verbose_name_plural': 'اعدادات'},
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='من نحن'),
        ),
    ]
