# Generated by Django 2.2.17 on 2021-02-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210208_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='facebook',
            field=models.URLField(default='#', verbose_name='رابط الفيسبوك'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='instagram',
            field=models.URLField(default='#', verbose_name='رابط الانستجرام'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='twitter',
            field=models.URLField(default='#', verbose_name='رابط تويتر'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='whatsapp',
            field=models.URLField(default='#', verbose_name='رقم الواتساب'),
        ),
    ]
