# Generated by Django 2.2.17 on 2021-02-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210208_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='hadaf',
            field=models.CharField(default='#', max_length=1000, verbose_name='الهدف'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='resala',
            field=models.CharField(default='#', max_length=1000, verbose_name='الرساله'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='roya',
            field=models.CharField(default='#', max_length=1000, verbose_name='الرؤيه'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='whyus1',
            field=models.CharField(default='#', max_length=1000, verbose_name='لماذا نحن -الخبره'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='whyus2',
            field=models.CharField(default='#', max_length=1000, verbose_name='لماذا نحن -الأمانه'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='whyus3',
            field=models.CharField(default='#', max_length=1000, verbose_name='لماذا نحن -الكفاءه'),
        ),
    ]
