# Generated by Django 2.2.17 on 2021-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210208_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='img2',
            field=models.ImageField(default='image.png', upload_to='', verbose_name='لوجو الموقع'),
        ),
    ]
