# Generated by Django 2.2.17 on 2021-02-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_siteedit_img2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteedit',
            options={'verbose_name': 'اعداد الموقع', 'verbose_name_plural': 'اعدادات الموقع'},
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='رقم الواتساب'),
        ),
    ]
