# Generated by Django 2.2.17 on 2021-02-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210208_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='send',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='send2',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='price',
            field=models.FloatField(default=0, help_text='اتركه كما هو وسيتم اضافته تلقائيا حسب سعر الخدمه. أو يمكنك اضافته بنفسك', verbose_name='المبلغ المستحق'),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='facebook',
            field=models.URLField(default='https://facebook.com', verbose_name='رابط الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='instagram',
            field=models.URLField(default='https://instagram.com', verbose_name='رابط الانستجرام'),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='twitter',
            field=models.URLField(default='https://twitter.com', verbose_name='رابط تويتر'),
        ),
    ]
