# Generated by Django 2.2.17 on 2021-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210208_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='img3',
            field=models.ImageField(default='image.png', upload_to='', verbose_name='صورة وصف الموقع'),
        ),
    ]
