# Generated by Django 2.2.17 on 2021-02-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_siteedit_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='img4',
            field=models.ImageField(default='image.png', upload_to='', verbose_name='صورة السلايدر1'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='img5',
            field=models.ImageField(default='image.png', upload_to='', verbose_name='صورة السلايدر2'),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='img6',
            field=models.ImageField(default='image.png', upload_to='', verbose_name='صورة السلايدر3'),
        ),
    ]
