# Generated by Django 2.2.17 on 2021-02-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210210_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='small',
            field=models.TextField(blank=True, null=True, verbose_name=' نبذه الفوتر'),
        ),
    ]
